### When done making changes here, run ipset-geoblock to update IPSet and test

# Countries we want to block
BADCN=(CN VN RU IN AF UA TW TH SK SI RO PL PK PH LV LU ID HU HR BD)

# Where we expect the APNIC list of delegated IPs to be
ARINLIST='/usr/share/vicibox-firewall/delegated-apnic-latest'

# IPSet rule to load the entries into
RULE='geoblock'
